apiVersion: apps/v1
kind: Deployment
metadata:  
  name: hello-deployment
  labels:
    app: go-test 
spec: 
  replicas: 2  
  selector:
    matchLabels:      
      app: go-test
  template:    
    metadata:      
      labels:        
        app: go-test  
    spec:      
      containers:      
        - name: go-test       
          image: "itsdenty/k8scicd"        
          resources:          
          requests:            
          cpu: 10m