- hosts: localhost
  connection: local
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml
    GOOGLE_APPLICATION_CREDENTIALS: ~jenkins/journal-app-1529931578045-883753fed26f.json
  tasks:  
   -  name: Deploy the service    
      k8s:      
        state: present      
        definition: ""    
        kubeconfig: '~jenkins/.kube/config'  
        validate_certs: no      
        namespace: default  
   -  name: Deploy the application 
      k8s:      
        state: present      
        validate_certs: no      
        namespace: default 
        kubeconfig: '~jenkins/.kube/config'      
        definition: ""