apiVersion: v1
kind: Service
metadata:  
  name: hello-svc
  labels:
    app: go-test
spec:  
  selector:   
    app: go-test
  ports:
    - protocol: TCP
      port: 80      
      targetPort: 8080      
      nodePort: 32000  
  type: NodePort