apiVersion: v1
kind: Service
metadata:  
  name: hello-svc
spec:  
  selector: 
    matchLabels:   
      role: app  
  ports:
    - protocol: TCP
      port: 80      
      targetPort: 8080      
      nodePort: 32000  
  type: NodePort